// 題庫（學校同款：判斷 sentence vs. fragment）
// 規則：句子簡短、初階、無 and/but/so/because/when/while 等連接詞。
// isSimple: true = 完整句 (Sentence), false = 片語/不完整 (Fragment)

const QUESTION_BANK = [
  // ===== 學校原題 8 題 =====
  { text: 'My name is Teacher Adam.', isSimple: true },
  { text: 'Talking to the man.', isSimple: false },
  { text: 'He is sleeping at the.', isSimple: false },
  { text: 'Do you want to build a snowman?', isSimple: true },
  { text: 'He ate lots of broccoli.', isSimple: true },
  { text: 'started to sing in the shower.', isSimple: false },
  { text: 'I scored 100% on my.', isSimple: false },
  { text: 'A fish in the sea.', isSimple: false },

  // ===== 正確的 Simple Sentences (50) =====
  { text: 'The dog runs.', isSimple: true },
  { text: 'She is happy.', isSimple: true },
  { text: 'He reads a book.', isSimple: true },
  { text: 'The sun is hot.', isSimple: true },
  { text: 'My mom cooks.', isSimple: true },
  { text: 'We play soccer.', isSimple: true },
  { text: 'The cat is black.', isSimple: true },
  { text: 'I like apples.', isSimple: true },
  { text: 'They are friends.', isSimple: true },
  { text: 'The baby cries.', isSimple: true },
  { text: 'My dad drives.', isSimple: true },
  { text: 'She sings well.', isSimple: true },
  { text: 'The boy is tall.', isSimple: true },
  { text: 'The room is clean.', isSimple: true },
  { text: 'The bus is late.', isSimple: true },
  { text: 'Birds can fly.', isSimple: true },
  { text: 'The phone is new.', isSimple: true },
  { text: 'It rains here.', isSimple: true },
  { text: 'My sister dances.', isSimple: true },
  { text: 'He eats rice.', isSimple: true },
  { text: 'She runs fast.', isSimple: true },
  { text: 'We are happy.', isSimple: true },
  { text: 'I love ice cream.', isSimple: true },
  { text: 'The fish swims.', isSimple: true },
  { text: 'The teacher smiles.', isSimple: true },
  { text: 'The girl laughs.', isSimple: true },
  { text: 'He kicks the ball.', isSimple: true },
  { text: 'We jump high.', isSimple: true },
  { text: 'The baby sleeps.', isSimple: true },
  { text: 'My grandma cooks.', isSimple: true },
  { text: 'The car stops.', isSimple: true },
  { text: 'The dog barks.', isSimple: true },
  { text: 'She drinks water.', isSimple: true },
  { text: 'He opens the door.', isSimple: true },
  { text: 'The bird sings.', isSimple: true },
  { text: 'The flowers grow.', isSimple: true },
  { text: 'The kids shout.', isSimple: true },
  { text: 'My mom smiles.', isSimple: true },
  { text: 'The cake is sweet.', isSimple: true },
  { text: 'The clock ticks.', isSimple: true },
  { text: 'The stars shine.', isSimple: true },
  { text: 'The train moves.', isSimple: true },
  { text: 'The cat sleeps.', isSimple: true },
  { text: 'He plays piano.', isSimple: true },
  { text: 'The girl claps.', isSimple: true },
  { text: 'The teacher talks.', isSimple: true },
  { text: 'The man runs.', isSimple: true },
  { text: 'The dog jumps.', isSimple: true },
  { text: 'We read books.', isSimple: true },
  { text: 'She draws well.', isSimple: true },
  { text: 'The soup is warm.', isSimple: true },

  // ===== 錯誤的（Fragment / 不完整）(50) =====
  { text: 'Like apples.', isSimple: false },
  { text: 'Running fast.', isSimple: false },
  { text: 'Very tall.', isSimple: false },
  { text: 'Happy girl.', isSimple: false },
  { text: 'Reads a book.', isSimple: false },
  { text: 'The sun hot.', isSimple: false },
  { text: 'Is happy.', isSimple: false },
  { text: 'My mom cooking.', isSimple: false },
  { text: 'They friends.', isSimple: false },
  { text: 'Baby cry.', isSimple: false },
  { text: 'Dad drive.', isSimple: false },
  { text: 'Singing well.', isSimple: false },
  { text: 'The boy tall.', isSimple: false },
  { text: 'Room clean.', isSimple: false },
  { text: 'Bus late.', isSimple: false },
  { text: 'Bird flying.', isSimple: false },
  { text: 'Phone new.', isSimple: false },
  { text: 'Rains here.', isSimple: false },
  { text: 'Sister dance.', isSimple: false },
  { text: 'Eat rice.', isSimple: false },
  { text: 'Run fast.', isSimple: false },
  { text: 'We happy.', isSimple: false },
  { text: 'Love ice cream.', isSimple: false },
  { text: 'Fish swim.', isSimple: false },
  { text: 'Teacher smile.', isSimple: false },
  { text: 'Girl laugh.', isSimple: false },
  { text: 'Kick ball.', isSimple: false },
  { text: 'Jump high.', isSimple: false },
  { text: 'Baby sleep.', isSimple: false },
  { text: 'Grandma cook.', isSimple: false },
  { text: 'Car stop.', isSimple: false },
  { text: 'Dog bark.', isSimple: false },
  { text: 'Drink water.', isSimple: false },
  { text: 'Open the door.', isSimple: false },
  { text: 'Bird sing.', isSimple: false },
  { text: 'Flower grow.', isSimple: false },
  { text: 'Kids shout.', isSimple: false },
  { text: 'Mom smile.', isSimple: false },
  { text: 'Cake sweet.', isSimple: false },
  { text: 'Clock tick.', isSimple: false },
  { text: 'Stars shine.', isSimple: false },
  { text: 'Train move.', isSimple: false },
  { text: 'Cat sleep.', isSimple: false },
  { text: 'Play piano.', isSimple: false },
  { text: 'Girl clap.', isSimple: false },
  { text: 'Teacher talk.', isSimple: false },
  { text: 'Man run.', isSimple: false },
  { text: 'Dog jump.', isSimple: false },
  { text: 'Read books.', isSimple: false },
  { text: 'Draw well.', isSimple: false },
  { text: 'Very happy.', isSimple: false }
];
