// 題庫：true = 是 simple sentence；false = 不是 simple sentence
const QUESTION_BANK = [
  // ✅ 正確 (1–30)
  { text: 'I like pizza.', isSimple: true },
  { text: 'She runs every morning.', isSimple: true },
  { text: 'The cat is black.', isSimple: true },
  { text: 'They are friends.', isSimple: true },
  { text: 'My mom cooks dinner.', isSimple: true },
  { text: 'He reads a book.', isSimple: true },
  { text: 'We play basketball.', isSimple: true },
  { text: 'The sun is bright.', isSimple: true },
  { text: 'This is my bag.', isSimple: true },
  { text: 'Dogs bark loudly.', isSimple: true },
  { text: 'I am happy.', isSimple: true },
  { text: 'She sings well.', isSimple: true },
  { text: 'The baby is crying.', isSimple: true },
  { text: 'My dad drives a car.', isSimple: true },
  { text: 'He eats breakfast at seven.', isSimple: true },
  { text: 'The teacher is kind.', isSimple: true },
  { text: 'We have two dogs.', isSimple: true },
  { text: 'My brother swims fast.', isSimple: true },
  { text: 'She goes to school.', isSimple: true },
  { text: 'They live in Taipei.', isSimple: true },
  { text: 'The phone is new.', isSimple: true },
  { text: 'It rains a lot here.', isSimple: true },
  { text: 'My sister dances.', isSimple: true },
  { text: 'He speaks English.', isSimple: true },
  { text: 'The room is clean.', isSimple: true },
  { text: 'I love ice cream.', isSimple: true },
  { text: 'The bus is late.', isSimple: true },
  { text: 'Birds can fly.', isSimple: true },
  { text: 'My grandma tells stories.', isSimple: true },
  { text: 'The boy is tall.', isSimple: true },

  // ❌ 錯誤 (31–60)
  { text: 'I like apples, and she likes oranges.', isSimple: false },
  { text: 'He studies hard, but he fails the test.', isSimple: false },
  { text: 'I am happy because I passed the exam.', isSimple: false },
  { text: 'She runs fast, and she sings well.', isSimple: false },
  { text: 'They play football while it rains.', isSimple: false },
  { text: 'The boy is smart, but lazy.', isSimple: false },
  { text: 'I went home, and I ate dinner.', isSimple: false },
  { text: 'My mom cooks dinner, and my dad washes dishes.', isSimple: false },
  { text: 'He didn’t come because he was sick.', isSimple: false },
  { text: 'She smiled when she saw me.', isSimple: false },
  { text: 'I like pizza, but I don’t like burgers.', isSimple: false },
  { text: 'The phone rang, and the baby cried.', isSimple: false },
  { text: 'We stayed home because it rained.', isSimple: false },
  { text: 'He is tall, and he is strong.', isSimple: false },
  { text: 'She went to school, but forgot her bag.', isSimple: false },
  { text: 'I like ice cream, and he likes cake.', isSimple: false },
  { text: 'They shouted when the game started.', isSimple: false },
  { text: 'He opened the door, and he walked out.', isSimple: false },
  { text: 'I studied hard, so I passed.', isSimple: false },
  { text: 'She was tired, but she kept working.', isSimple: false },
  { text: 'We played outside until it was dark.', isSimple: false },
  { text: 'The dog barked because it was hungry.', isSimple: false },
  { text: 'I want to go, but I can’t.', isSimple: false },
  { text: 'She sang while he played guitar.', isSimple: false },
  { text: 'He ran fast, so he won the race.', isSimple: false },
  { text: 'They stayed home because it rained.', isSimple: false },
  { text: 'I wanted to call, but I forgot.', isSimple: false },
  { text: 'She laughed when she heard the joke.', isSimple: false },
  { text: 'He tried hard, but he failed.', isSimple: false },
  { text: 'We ate dinner after we finished homework.', isSimple: false }
];
